In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
config_file='ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
frozen_model='frozen_inference_graph.pb'

In [3]:
model=cv2.dnn_DetectionModel(frozen_model,config_file)
file_name='Labels.txt'
with open(file_name,'rt')as fpt:
    classLabels=fpt.read().rstrip('\n').split('\n')

In [4]:
print(classLabels)

['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']


In [5]:
# print(len(classLabels))

In [6]:
model.setInputSize(320,320)
model.setInputScale(1.0/127.5)
# model.setInputMean(127.5,127.5,127.5)
model.setInputMean(127.5)
model.setInputSwapRB(True)

< cv2.dnn.Model 0000019E8EDF3910>

In [7]:
# img=cv2.imread('car.jpg')

In [8]:
# plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

In [9]:
# ClassIndex,confidence,bbox=model.detect(img,confThreshold=0.5)

In [10]:
# print(ClassIndex)

In [11]:
# font_scale=3
# font=cv2.FONT_HERSHEY_PLAIN
# for classInd,conf,boxes in zip(ClassIndex.flatten(),confidence.flatten(),bbox):
#     cv2.rectangle(img,boxes,(255,0,0),2)
#     cv2.putText(img,classLabels[classInd-1],(boxes[0]+10,boxes[1]+40),font,fontScale=font_scale,color=(0,255,0),thickness=3)

In [12]:
# plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

In [ ]:
# cap=cv2.VideoCapture("Video.mp4")
cap=cv2.VideoCapture(1)

if not cap.isOpened():
    cap=cv2.VideoCapture(0)
if not cap.isOpened():
    raise IOError("Can't open WebCam")
    
font_scale=3
font=cv2.FONT_HERSHEY_PLAIN

while True:
    ret,frame=cap.read()
    
    ClassIndex,confidence,bbox=model.detect(frame,confThreshold=0.55)
    
    print(ClassIndex)
    if(len(ClassIndex)!=0):
        for ClassInd,conf,boxes in zip(ClassIndex.flatten(),confidence.flatten(),bbox):
            if(ClassInd<=80):
                cv2.rectangle(frame,boxes,(255,0,0),2)
                cv2.putText(frame,classLabels[ClassInd-1],(boxes[0]+10,boxes[1]+40),font,fontScale=font_scale,color=(0,255,0),thickness=3)
    
    cv2.imshow('Object Detection Tutorial',frame)
        
    if cv2.waitKey(2) & 0xFF ==ord('q'):
        break
            
cap.release()
cv2.destroyAllWindows()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[10]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[10]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[10]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
(

[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87]
[87 87]
[87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87]
[87 87 87]
[87 87 87]
[87 87 87]
[87 87 87]
()
()
()
()
()
()
()
[18]
()
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[ 1 18]
[ 1 18]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[ 1 18]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[ 1 18]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[ 1 18]
[ 1 18]
[ 1 18]
[ 1 18]
[ 1 18]
[1]
[1]
[1]
[1]
[1]
[1]

[1]
[1]
[1]
[1]
()
()
()
()
()
()
()
()
()
()
[16]
()
[85]
[85]
()
[85]
()
[85]
[85]
()
()
()
()
()
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
()
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
()
[85]
[85]
[85]
[85]
[85]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[85]
[85]
[85]
()
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
()
[85]
[85]
[85]
[85]
[85]
[85]
()
()
()
()
()
()
()
()
()
[85]
()
()
()
()
[85]
[16 16]
[16]
()
()
()
()
()
[28]
()
()
()
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
()
()
[18]
[18]
()
()
[18]
()
[1 1]
[1 1]
[1 1]
[1]
[1 1]
[1 1]
[1]
[1 1]
[1 1]
[1]
[1]
[1 1]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[1]
[1]
[1]
[1]
[1 1]
[1]
[1 1]
[1 1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
()
[1]
[1]
[1]
[1]
[1]
[16]
[16]
[1]
[1]
[1]
[1]
[85  1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[ 1 16]
[17]
[17]
[17]
[17]
[17]
[17]
[17]
[17]
[17]
[17]
[17]
[17 17]
[1]
()
()
[28]
[28]
[1]
[1]
()
()
()
()
()
()
()


[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[86]
[86]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[ 1  1  1 65  1]
[ 1  1  1 65  1]
[ 1  1 65  1  1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[ 1  1  1  1 65]
[ 1  1  1  1 65]
[ 1  1  1  1 65]
[ 1  1 65  1]
[ 1  1 65  1]
[ 1  1 65  1]
[ 1  1  1 65]
[ 1  1  1 65]
[ 1  1  1 65]
[ 1  1  1 65]
[ 1  1  1 65]
[ 1  1  1 65]
[1 1 

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
[85]
()
()
()
[85]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[85]
[85]
[85]
[85]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[1 1]
[ 1  1 72]
[ 1 72]
()
()
()
[1]
[1]
[1]
[1]
[1]
()
()
[1]
[1]
()
()
()
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1]
[1 1]
[1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1]
[1 1 1]
[1]
[1]
[1]
[1 1]
[1 1]
[1 1]
[1]
[1]
[1]
[1 1]
[1 1]
[1]
[1]
